### ISSUE TITLE
Memory Consumption Grows When Running ORB_SLAM2 for long time in same environment

### ISSUE THREAD

**Issue by CTTC** [raulmur/ORB_SLAM2#350]
I have tried to run ORB-SLAM2 RGBD with a bag (played in **loop**). The memory consumption just continued to grow as the program ran. I guess that's because even though there is a KeyFrameCulling and MapPointCulling in LocalMapping, these instances' memory on heap did not get released as there is no **delete** to match **new**. I tried to add `delete pKF` after `pKF->SetBadFlag();` in `LocalMapping.cc`, but did not succeed (Segmentation fault (core dumped)). 

Here is the backtrace of the core dump file in gdb:
```bash
#0  0x00007f069daf9428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f069dafb02a in __GI_abort () at abort.c:89
#2  0x00007f069db3b7ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7f069dc542e0 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007f069db43e0a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, str=0x7f069dc543f0 "double free or corruption (out)", action=3) at malloc.c:5004
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3865
#5  0x00007f069db4798c in __GI___libc_free (mem=<optimized out>) at malloc.c:2966
#6  0x00007f069e75d0bb in std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >::~vector (
    this=0x7f064affc8e0, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/stl_vector.h:424
#7  std::_Destroy<std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > > (__pointer=<optimized out>)
    at /usr/include/c++/5/bits/stl_construct.h:93
#8  std::_Destroy_aux<false>::__destroy<std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >*> (
    __last=<optimized out>, __first=0x7f064affc8e0) at /usr/include/c++/5/bits/stl_construct.h:103
#9  std::_Destroy<std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >*> (__last=<optimized out>, 
    __first=<optimized out>) at /usr/include/c++/5/bits/stl_construct.h:126
#10 std::_Destroy<std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >*, std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > > (__last=0x3ec, __first=<optimized out>) at /usr/include/c++/5/bits/stl_construct.h:151
#11 std::vector<std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > >, std::allocator<std::vector<std::vector<unsigned long, std::allocator<unsigned long> >, std::allocator<std::vector<unsigned long, std::allocator<unsigned long> > > > > >::~vector (this=0xdcc3348, __in_chrg=<optimized out>)
    at /usr/include/c++/5/bits/stl_vector.h:424
#12 ORB_SLAM2::KeyFrame::~KeyFrame (this=0xdcc2de0, __in_chrg=<optimized out>) at /home/chentao/software/ORB_SLAM2/src/KeyFrame.cc:65
#13 0x00007f069e76a311 in std::unique_lock<std::mutex>::lock (this=<synthetic pointer>) at /usr/include/c++/5/mutex:479
#14 std::unique_lock<std::mutex>::unique_lock (__m=..., this=<synthetic pointer>) at /usr/include/c++/5/mutex:415
#15 ORB_SLAM2::Map::InformNewBigChange (this=0x562c) at /home/chentao/software/ORB_SLAM2/src/Map.cc:77
```

**Comment by ns15417** [comment]
@taochenshh hey, what happend and why did you close this issue
